name: Api Docs deployment

on:
  push:
    branches:
      # - master
      - MRETS-21958
env:
    REPOSITORY: mrets/api-docs

jobs:
  open_pr:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
     - name: Clone the repository
       uses: actions/checkout@v6
       with:
        repository: ${{ env.REPOSITORY}}
        token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
        ref: develop

     - name: Clean Working Directory
       run: |
            git checkout develop
            git fetch --all
            git reset --hard origin/develop
            git checkout -b mrets-testing
            
            git config --global user.email "sofia.paoli@tarmac.io

            git config --global user.name ${{ github.actor }}
            git commit --allow-empty -m "Update changes from the operating-procedures repository"
            
     - name: Push release branch
       run: git push origin mrets-testing

     - name: Create a PR against develop
       env: 
        GH_TOKEN: ${{ secrets.EXTERNAL_REPO_TOKEN }}
       run: |
            gh pr create --base develop --head mrets-testing --title "Testing" --body "Testing - PR Auto-generated by Github Actions" --repo github.com/mrets/api-docs 