name: Sync Operating Procedures dependency with API Docs repository

on:
  push:
    branches:
      - master
      
env:
    REPOSITORY: mrets/api-docs
    BRANCH: MRETS-sync-operating-procedures-dependency
    RELEASE_BRANCH: develop-into-master-operating-procedures


jobs:
  open_pr:
    name: Sync
    runs-on: ubuntu-latest
    steps:
     - name: Clone the repository
       uses: actions/checkout@v6
       with:
        repository: ${{ env.REPOSITORY}}
        token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
        ref: develop
        fetch-depth: 0

     - name: Configure Git
       run: |
          git config --global user.email "itaccounts@mrets.org"
          git config --global user.name ${{ github.actor }}

     - name: Push to develop branch
       run: |
            git checkout develop
            git pull origin develop
            git checkout -b ${{ env.BRANCH}}
            git commit --allow-empty -m "Sync changes from the operating-procedures repository"
            git checkout develop
            git merge ${{ env.BRANCH}} --ff-only
            git push origin develop

     - name: Clean Working Directory
       run: |
            git fetch origin
            git checkout develop
            git pull origin develop
            git checkout -b ${{ env.RELEASE_BRANCH}}
            git merge origin/master
            git push origin ${{ env.RELEASE_BRANCH}}

     - name: Create a PR to master branch
       env: 
        GH_TOKEN: ${{ secrets.EXTERNAL_REPO_TOKEN }}
       run: |
            gh pr create --base master --head ${{ env.RELEASE_BRANCH}} --title "Automated sync from the Operating Procedures repository" --body "This pull request was automatically generated after changes were merged into the Operating Procedures repository - PR Auto-generated by Github Actions" --repo github.com/mrets/api-docs --reviewer tinchodipalma,lirimkrosa,sofiapaoli2022
